#!/usr/bin/env python3
"""transpiler.py — Entry point for the XC -> C99 transpiler.

Module layout:
  xc_types.py      — Dataclasses (Param, FunctionDef, GenericFunctionDef, StructDef),
                     built-in type maps, replace_builtin_types
  xc_utils.py      — Brace/paren matching, parse_params, tokeniser, misc transforms
  xc_structs.py    — Struct parsing, inheritance, C emission, static accesses
  xc_methods.py    — Method body rewriting, generate_method_impl, rewrite_method_calls
  xc_conditions.py — Condition rewriting: and/or/not, chained comparisons, intervals
  xc_references.py — C++ style reference (TYPE& name) -> pointer transformation
  xc_generics.py   — Generic/template functions and explicit specializations
  xc_misc.py       — cstrings, new/delete, overloading, default params,
                     regex directives, header guards
"""

import re
import sys

from xc_types      import replace_builtin_types
from xc_utils      import fix_pointer_declarations, replace_binary_literals
from xc_structs    import (extract_structs, normalize_typedef_structs,
                           rewrite_static_accesses, rewrite_struct_value_casts,
                           strip_stale_init_calls)
from xc_methods    import rewrite_method_calls
from xc_conditions import rewrite_conditions
from xc_references import replace_references
from xc_generics   import (extract_generic_functions, extract_specializations,
                            instantiate_generics)
from xc_misc       import (lift_includes, replace_cstring_declarations,
                           replace_new_delete, replace_header_guards,
                           apply_regex_directives, expand_default_params,
                           mangle_overloaded_functions, rewrite_cstring_ops)


HEADER_BASE   = "/* Auto-generated by xc transpiler — C99 */\n"
HEADER_STDLIB = "#include <stdlib.h>\n"


def transpile(source: str) -> str:
    # --- Pre-processing directives ---
    source = apply_regex_directives(source)
    source = replace_header_guards(source)

    # Strip comments (preserve newlines for line-number accuracy)
    # Block comments first, then line comments
    def _strip_comments(src: str) -> str:
        result = []
        i = 0; n = len(src)
        while i < n:
            # String literal — skip over it unchanged
            if src[i] == '"':
                j = i + 1
                while j < n:
                    if src[j] == '\\': j += 2; continue
                    if src[j] == '"':  j += 1; break
                    j += 1
                result.append(src[i:j]); i = j
            elif src[i] == "'":
                j = i + 1
                while j < n:
                    if src[j] == '\\': j += 2; continue
                    if src[j] == "'":  j += 1; break
                    j += 1
                result.append(src[i:j]); i = j
            # Block comment
            elif src[i:i+2] == '/*':
                j = src.find('*/', i+2)
                end = (j + 2) if j != -1 else n
                # Preserve newlines
                result.append(re.sub(r'[^\n]', ' ', src[i:end]))
                i = end
            # Line comment
            elif src[i:i+2] == '//':
                j = src.find('\n', i)
                end = j if j != -1 else n
                result.append(' ' * (end - i))
                i = end
            else:
                result.append(src[i]); i += 1
        return ''.join(result)
    source = _strip_comments(source)

    # --- Literal transforms ---
    source = replace_binary_literals(source)
    source, needs_stdlib = replace_new_delete(source)
    source = replace_builtin_types(source)
    source = replace_cstring_declarations(source)

    # --- Generic / template functions ---
    # 1. Extract template definitions (lazy — emit only when called)
    generic_templates, source    = extract_generic_functions(source)
    # 2. Extract explicit specializations (eager — emit immediately)
    specialization_impls, source = extract_specializations(source, generic_templates)
    # 3. Rewrite call sites; lazily instantiate any non-specialised calls
    generic_impls, source        = instantiate_generics(source, generic_templates,
                                                        specialization_impls)

    # --- Struct normalisation and extraction ---
    _source_before_normalize = source
    source = normalize_typedef_structs(source)

    _td_scan = re.compile(
        r'\btypedef\s+(?:proto\s+)?struct\s+(\w+)\s*'
        r'(?:extends\s+(?:struct\s+)?(\w+)\s*)?\{',
        re.MULTILINE
    )
    _typedef_origin = {m.group(1) for m in _td_scan.finditer(_source_before_normalize)}

    source, extra_includes = lift_includes(source)
    source = expand_default_params(source)
    structs, source = extract_structs(source, typedef_origin=_typedef_origin)

    # --- Reference and method-call rewriting ---
    _ref_struct_names = {sd.name for sd in structs} | _typedef_origin
    source = replace_references(source, known_struct_names=_ref_struct_names)
    source = rewrite_method_calls(source, structs)

    # --- Misc cleanup passes ---
    source = fix_pointer_declarations(source)
    source = rewrite_conditions(source)
    source = expand_default_params(source)
    source = mangle_overloaded_functions(source)
    source = strip_stale_init_calls(source, structs)
    source = rewrite_cstring_ops(source)
    source = rewrite_static_accesses(source, structs)
    source = rewrite_struct_value_casts(source, structs)

    # --- Assemble output ---
    header = HEADER_BASE
    if needs_stdlib:    header += HEADER_STDLIB
    if extra_includes:  header += '\n'.join(extra_includes) + '\n'
    header += '\n'

    out_parts = [header]
    for s in structs:
        out_parts.append(f'struct {s.name};')
    if structs:
        out_parts.append('')

    # Specializations first, then lazy generics, then user source
    injected = '\n'.join(filter(None, [
        '\n'.join(specialization_impls.values()) if specialization_impls else '',
        generic_impls,
    ]))
    if injected.strip():
        out_parts.append(injected)

    out_parts.append(source)
    return '\n'.join(out_parts)


def main():
    if len(sys.argv) < 2:
        print("Usage: transpiler.py <input.xc> [output.c]")
        sys.exit(1)

    input_path  = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else input_path.replace('.xc', '.c')

    with open(input_path, 'r') as f:
        source = f.read()

    try:
        result = transpile(source)
    except (SyntaxError, NameError, TypeError) as e:
        print(f"Transpiler error: {e}", file=sys.stderr)
        sys.exit(1)

    with open(output_path, 'w') as f:
        f.write(result)

    print(f"Transpiled: {input_path} -> {output_path}")


if __name__ == '__main__':
    main()
